services:
  db:
    image: postgres:17-alpine
    container_name: vetapp_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'  # Puerto para PostgreSQL cambiado a 5433
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_vetapp
    restart: always
    ports:
      - "5051:80"  # Puerto de pgAdmin cambiado a 5051
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data:
