spring.application.name=Vetappbackend
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Elimina esta línea
# Configuración del servidor
server.port=9000
server.error.whitelabel.enabled=false
server.error.include-message=always

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/vetapp

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

# Configuración de logging
logging.level.root=INFO